### ISSUE TITLE
Minimize syntax differences

### ISSUE THREAD

**Issue by retyui** [Khan/flow-to-ts#103]
### 1) `type Fn = () => void`

In TS `void` is can be any (`Promise`, `null`, `number` ...)
But in Flow.js void is only `undefined`

```js
function test(fn: () => void){}

test(() => {});
test(async () => 1); // Flow.js error 
test(() => '1'); // Flow.js error
```

[Play TS...](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABFApgZygCmGAXIzASkQF4A+RANzhgBNCBvAKCYF8WnUNMBDNAT0gFi5RAEZCAbk7osRUhQaspM7vNEByMRqlA)

[Try  Flow.js...](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCmGAXIzASkQF4A+RANzhgBNCBvAKCYF8XUNMjSKHXCAbiacsAQzQBPSAWLlEARiGIA9CsQAxADZwA7gDoAVmkQoATmbhnEI9Fh7yA5AsfK1mnQeOmLVoA)

---

### 2)  { readOnlyMethod(): any  }

```js
type  T = {
	t(): number;
}

var test: T = {t(){return 1}};

test.t = () => 2; // Flow: error `t` is read only
```

[Play TS...](http://www.typescriptlang.org/play/#code/C4TwDgpgBFAqUF4oG8BQBIYAKAlALigDsBXAWwCMIAnAblQF9VUA3AQyqmAgGdgD4kybDmRUIwYlUJQAjPXp0mXXgDpgiKLkQA+KACYaQA)

[Try Flow.js...](https://flow.org/try/#0C4TwDgpgBFAqUF4oG8BQBIYAKAlALigDsBXAWwCMIAnAblQF9VUA3AQyqmAgGdgD4kybDmRUIwYlUJQAjPXp0mXXgDpgiKLkQA+KACYaUAPRGo1KgHsO6gJbcoY1gBMoFwgBsQQA)

**Comment by k4b7** [comment]
> In TS void is can be any (Promise, null, number ...)

This is only true in certain situations.

> 2) { readOnlyMethod(): any }

I'm not sure why flow decided to make methods readonly when other properties aren't readonly.  Also, why does does rewriting `T` in the following way making `t` not readonly?
```
type  T = {
	t: => () number;
}
```

There are other things that `flow` treats as a problem that TypeScript doesn't.  Another example is unsafe assignments are allowed, e.g.
```
class Animal {};
class Cat extends Animal { meow() {} }
class Dog extends Animal { woof() {} }

let animals: Animal[] = [];
let cats: Cats[] = [new Cat];

animals = cats;

animals.push(new Dog); // whoops
```

**Comment by retyui** [comment]
@kevinbarabash 
> There are other things that flow treats as a problem that TypeScript doesn't. 

I only affect syntax mismatch

> This is only true in certain situations.

Give me an example when is not true!

> I'm not sure why flow decided to make methods readonly when other properties aren't readonly.

```
// methods in flow always read-only
type T = {
    method(): void // read-only
}

// but a function can be write/read
type T2 = {
    funcProp: () => void // wriet and read
}
```

**Comment by k4b7** [comment]
> Give me an example when is not true!

TS will complain about `const a: void = "hello";`  It seems like the issue with `void` is only with the return types.  `const b: () => void = () => { return 5; }` also doesn't cause an error in TS.

> // methods in flow always read-only

TIL.

I think the second issue you reported can be fixed.  The first one though I believe requires changes to TS itself.

**Comment by retyui** [comment]
@kevinbarabash 
> It seems like the issue with void is only with the return types.

That is true. In my opinion, the converter should generate next code (for return types ONLY)

Flow:
```js
// @flow
type Fn = () => mixed;
type Fn2 = () => void;
```

TS:
```js
type Fn = () => void;
type Fn2 = () => undefined;
```
