### ISSUE TITLE
Unions as Obejct indexers

### ISSUE THREAD

**Issue by davidmh** [Khan/flow-to-ts#108]
First, thank you for publishing this tool, my team is very excited to make the switch. We all appreciate your efforts.

When using aliases or union types, the translation as an object indexer doesn't work. [Example](https://flow-to-ts.netlify.com/#code=Ly8gQGZsb3cKdHlwZSBNeUN1c3RvbUtleSA9IHN0cmluZyB8IG51bWJlcgoKdHlwZSBNeUN1c3RvbU9iamVjdCA9IHsKCVtNeUN1c3RvbUtleV06IG51bWJlciwKfQoKdHlwZSBEYXkgPSAid2Vla2RheSIgfCAid2Vla2VuZCI7Cgp0eXBlIERheVN0YXRzID0gewogICAgW0RheV06IG51bWJlcgp9&prettier=1&semi=1&singleQuote=0&tabWidth=4&trailingComma=all&bracketSpacing=0&arrowParens=avoid&printWidth=80&inlineUtilityTypes=0)

Current output: 

```typescript
type DayStats = {
    [key: Day]: number;
};
```

This [throws errors](http://www.typescriptlang.org/play/#code/C4TwDgpgBAsiDCBXAzsA9gWwNIRFAvFKgE4CWAdgOZQA+U5iGARhMQNwBQHoksCK6DAHkmAKwgBjYASgBvDlEVQA2gGtcALj5JUmHCAC6Whs1acAvp27hoAEQCGeQgCIA7hAiqAJo+e0obh7q5F7OVjx2jgDKwPbAyDLySirqIFoOhsaMLOwcllwSaOSoUD4gMXHI6dGx8YkKSu6eZVoADAA0DYpNwV5aAIyteUA) with both aliases and union types,

Expected output:

```typescript
type DayStats = {
    [key in Day]: number;
};
```

Or even better:

```typescript
type DayStats = Record<Day, number>;
```

I've been playing with the `ObjectTypeIndexer` transformation, but I'm guessing it shouldn't be a `TSTypeLiteral` in the first place.

According to [this example](https://astexplorer.net/#/gist/b70a899ee34c67cba3050271c352daa9/58b1f97178b34f2ea264a466ed888409f245453f), I should be looking for a `TSMappedType`.

Any pointers?

**Comment by k4b7** [comment]
I didn't realize that.  Nice find.  Unfortunately this complicates things because now we'll have to resolve type aliases to know if something is a union or not. 😞

**Comment by k4b7** [comment]
> Any pointers?

I'd try solving it for an inline union first, e.g.
```
type DayStats = {
    [key: string | number],
};
```
and worry about type aliases after that's working.

**Comment by lautis** [comment]
Inline union gives an error too. Wouldn't using `Record` work everywhere?

It's defined

```typescript
type Record<K extends keyof any, T> = {
    [P in K]: T;
}
```

**Comment by k4b7** [comment]
There's a difference in semantics though. `[P in K]: T;` requires all keys to exist whereas `[key: Day]: number;` in Flow all of the keys are optional.  I think we'll want `[P in K]?: T;` to match Flow's semantics.

**Comment by palexs** [comment]
This is still an issue when running `flow-to-ts` tool. However, when I use https://flow-to-ts.netlify.app/ it does the transformation correctly.

**Comment by k4b7** [comment]
@palexs try updating to 0.1.6.
