### ISSUE TITLE
Doesn't remove "@flow strict" and "@flow strict-local" pragmas

### ISSUE THREAD

**Issue by serhalp** [Khan/flow-to-ts#123]
Given these three files:

```js
// @flow
null;
```

```js
// @flow strict-local
null;
```

```js
// @flow strict
null;
```

The expected behavior is for all three ported files to become:
```js
null;
```

All three are correctly renamed to `.ts` and translated, but only the first file has its first line removed.

I assume this is a trivial fix! Tweak [this logic](https://github.com/Khan/flow-to-ts/blob/7438d9f983ecbe6964c4c7365a268fe0e79076c5/src/transform.js#L116-L128)? I could take a crack at it.

P.S. at the same time, if it's easy, it would be great to actually delete the line rather than blank it out (i.e. don't leave a blank line).

**Comment by k4b7** [comment]
@serhalp thanks for raising this issue.  As you suggested, it should be pretty easy to fix.  As for the P.S., I think it does delete the line or maybe it's prettier that does that (sorry, it's been a while since I've looked at this code).  In the demo, the lines get removed.

**Comment by k4b7** [comment]
I've assigned this this ticket to you.  I hope that's okay.

**Comment by joebowbeer** [comment]
I observe that comments of the form `/** @flow */` are not removed either.
