### ISSUE TITLE
Callable objects not converted

### ISSUE THREAD

**Issue by egeriis** [Khan/flow-to-ts#128]
Hi :wave:

Looks like a great project, that we'll use in the future. Just wanted to raise an issue, since I toyed a bit around with some examples in your playground, and it appears that [callable](https://basarat.gitbooks.io/typescript/docs/types/callable.html) objects/interfaces are not supported:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/579824/68307070-eaaf0380-00aa-11ea-9fa3-d655069770da.png">

It also doesn't appear to be part of the roadmap. Is it possible to add this? I also wondered if objects should be converted to interfaces, since that seems to be the "right way" to do it in TypeScript?

[Link to repro](https://flow-to-ts.netlify.com/#code=dHlwZSBDU1MgPSAoKSA9PiBzdHJpbmc7CnR5cGUgTWl4aW48TW9kaWZpZXJzPiA9IHsKICAoKTogQ1NTLAogIG1vZGlmaWVyczogQXJyYXk8TW9kaWZpZXJzPiwKICBbTW9kaWZpZXJzXTogTWl4aW48TW9kaWZpZXJzPgp9Ow==&prettier=1&semi=1&singleQuote=0&tabWidth=4&trailingComma=all&bracketSpacing=0&arrowParens=undefined&printWidth=80&inlineUtilityTypes=0)

Thanks.

**Comment by k4b7** [comment]
I didn't realize this syntax existed in Flow.  It seems like TypeScript supports callables in object types as well interfaces so we should probably keep interfaces as interfaces and object types as object types.

**Comment by k4b7** [comment]
I've updated the roadmap to include this issue.

**Comment by egeriis** [comment]
Lovely, thank you!
