### ISSUE TITLE
Mixing function type throws SyntaxError

### ISSUE THREAD

**Issue by joebowbeer** [Khan/flow-to-ts#132]
The following throws SyntaxError:

```
// @flow
type Thing = string | (foo: string) => any
```

```
SyntaxError: ')' expected. (2:27) 1 | > 2 | type Thing = string | (foo: string) => any; | ^
```

https://flow-to-ts.netlify.com/#code=Ly8gQGZsb3cKdHlwZSBUaGluZyA9IHN0cmluZyB8IChmb286IHN0cmluZykgPT4gYW55Cg==&prettier=1&semi=1&singleQuote=0&tabWidth=4&trailingComma=all&bracketSpacing=0&arrowParens=avoid&printWidth=80&inlineUtilityTypes=0

**Comment by joebowbeer** [comment]
Workaround:

```
// @flow
type Foo = (foo: string) => any
type Thing = string | Foo
```

**Comment by k4b7** [comment]
`@babel/parser` probably needs updating.

**Comment by k4b7** [comment]
I can't reproduce this anymore in the playground.  Please give the latest release a try.
