### ISSUE TITLE
How important it preserving the position of comments in the output

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/flow-to-ts#147]
Being able to position comments properly in the output requires a fork of @babel/generator.  Keeping this fork up to date is going to be a lot of work, but we'll need to update eventually so that we can support new features.

I think there might be an alternative approach to having the comments appear in the correct locations which is to do a second pass on the output and reposition any comments that ended up the wrong location.

**Comment by k4b7** [comment]
I've gone ahead with dropping the vendored version of `@babel/generator` that was in the codebase.  This has result in some differences in whitespace between the source and output.  I had to do a little bit of work to get comments in the right place but was able to do this without modifications to `@babel/generator` itself.
