### ISSUE TITLE
Replace ElementConfig with JSX.LibraryManagedAttributes

### ISSUE THREAD

**Issue by SBoudrias** [Khan/flow-to-ts#155]
Missing transform for compatibility with TS:

```diff
- type TestProps = React.ElementConfig<Test>;
+ type TestProps = JSX.LibraryManagedAttributes<typeof Test, Test["props"]>;
```

I found most details on https://github.com/Microsoft/TypeScript/issues/26704

**Comment by k4b7** [comment]
In order to handle functional components the conversion will need to be:
```
type TestProps = React.ElementConfig<typeof Test>;
type TestProps = JSX.LibraryManagedAttributes<
    typeof Test,
    React.ComponentProps<typeof Test>
>;
```

**Comment by k4b7** [comment]
Older versions of Flow allowed passing the component directly to `React.ElementConfig<>`, but now you have to pass the component's type.
