### ISSUE TITLE
optional types

### ISSUE THREAD

**Issue by mr-piratman** [Khan/flow-to-ts#156]
interface Foo {
colour: ?string
}

interface Foo {
colour?: string
}

actually I have the fix. 
I just don't have permissions for a pushing my branch.
contact me. if you wish.

**Comment by lucasff** [comment]
@mr-piratman you need to fork the repo and submit a pull request to this repo. you don't know how to do that?

**Comment by mr-piratman** [comment]
Nope.
i pulled the repo, created a branch.
Changed it but i couldnt push.

Usualy i do the PR from github GUI after I have pushed my branch.

**Comment by k4b7** [comment]
@mr-piratman could you describe the issue first.  I copy/pasted the code snippets from your original post into the playground and everything seems to be working as expected.

https://flow-to-ts.netlify.com/#code=Ly8gQGZsb3cKaW50ZXJmYWNlIEZvbyB7CiAgICBjb2xvdXI/OiBzdHJpbmcKfQoKaW50ZXJmYWNlIEJhciB7CiAgICBjb2xvdXI6ID9zdHJpbmcKfQ==&prettier=1&semi=1&singleQuote=0&tabWidth=4&trailingComma=all&bracketSpacing=0&arrowParens=undefined&printWidth=80&inlineUtilityTypes=0
