### ISSUE TITLE
Handle historical types

### ISSUE THREAD

**Issue by gomesalexandre** [Khan/flow-to-ts#185]
"For historical reasons", flow has the `Object` and ` Function` types
![image](https://user-images.githubusercontent.com/17035424/100553797-505ec680-3290-11eb-893f-a6899d75cec8.png)

- The former should be typed `{ [key: string]: any}` 
- The latter should be typed `(...args: Array<any>) => any` 

It's probably a good idea to add a `test/fixtures/convert/historical-types` folder, as there isn't anything like this in the codebase so far.

**Comment by k4b7** [comment]
I've published a new version of the package to nom with these changes.
