### ISSUE TITLE
Handle private React types

### ISSUE THREAD

**Issue by gomesalexandre** [Khan/flow-to-ts#195]
q.v  https://github.com/Khan/flow-to-ts/blob/32cb7cd049b96467a5d967d699e20d2d8c7b3dfc/src/transform.js#L105

We could build a mapping, like this

```js
React$Node: 'ReactNode',
React$Element: 'ComponentType<any>',
React$ComponentType: 'ComponentType<any>',
```

And then construct a matching node e.g for `React$Node`, the node would convert to `React.ReactNode` code.
We would of course have to check if React is imported in the current file, if not, import it using ESM syntax. 

Obviously, `any` is just for the example and we should handle the generics of each type, for instance, `React$Element` accepts `ElementType` as a generic:
https://github.com/facebook/flow/blob/master/lib/react.js#L178

The full list of private react types is available in the aforementionned file.

**Comment by k4b7** [comment]
Thanks for filing a ticket for this.

**Comment by k4b7** [comment]
@gomesalexandre is mapping `React$Element` to `ComponentType<any>` correct?  Does TypeScript's React library definitions treat elements and components as the same thing?
