### ISSUE TITLE
Use `Record<string, any>` instead of `Object`

### ISSUE THREAD

**Issue by aminya** [Khan/flow-to-ts#198]
Currently, the code is converted into a verbose syntax:
```ts
{
   [key: string]: any
 }
```

while this can be written just as `Record<string, any>`

[An example of manual editing that is needed to replace the verbose syntax](https://github.com/steelbrain/linter/pull/1718/commits/d6a561c81fcb973eb757e58058c6670b2f0d46d5)

**Comment by k4b7** [comment]
Good call.  This seems like a simple change to make the output more idiomatic.
