### ISSUE TITLE
Convert suppression comments

### ISSUE THREAD

**Issue by k4b7** [Khan/flow-to-ts#207]
e.g.
```
// $FlowIgnore -> @ts-ignore
// $FlowExpectError -> @ts-expect-error
// $FlowFixMe -> @ts-expect-error
```
There is no `@ts-fix-me`, see https://github.com/microsoft/TypeScript/issues/28796

**Comment by k4b7** [comment]
@jtbandes fixing the comment positioning issue will be important for this this work right.

**Comment by k4b7** [comment]
Flow now supports having multiple line comment suppressions for a single expression, e.g.
```
// $FlowFixMe[prop-missing]
// $FlowFixMe[incompatible-exact]
// $FlowFixMe[incompatible-type]
studentList={studentList}
```
When handling situations like this we'll probably want to merge these into a single comment, e.g.
```
// $ts-expect-error: prop-missing, incompatible-type
```
I think we can drop `$FlowFixMe[incompatible-exact]` completely since TypeScript doesn't support exact types.

**Comment by k4b7** [comment]
There may be text after the error code, e.g.
```
// $FlowFixMe[prop-missing]: the `foo` prop is missing
```
If we're merging multiple comments like this we'll need to figure out a good pattern for doing so.

**Comment by k4b7** [comment]
It looks like `@ts-ignore` and `@ts-expect-error` must be in single line comments directly before the issue so we'll have to handle flow suppressions from block comments accordingly.

**Comment by meandmax** [comment]
Shouldn't suppressions be stripped as they might be completely different or not needed in TS? :)

**Comment by k4b7** [comment]
@meandmax that's a good point.  If we strip out all of the flow suppressions it would be good to have a way to automatically add TypeScript suppressions in to the generated code.  I wonder if there's tooling out there that already does this.

**Comment by k4b7** [comment]
Closing in preference of #284.
