### ISSUE TITLE
jscodemod is required but not specified in the doc or package.json

### ISSUE THREAD

**Issue by dephiros** [Khan/flow-to-ts#269]
Problem:
- I just started to test `flow-to-ts` today and the cli return an error about missing `jscodemod`

Expected:
- We should specify jscodemod as either a dependency or peeerDependency and update the doc

**Comment by k4b7** [comment]
@dephiros can you include a copy the error and any stack trace from the error?  Also, which version are you running?

**Comment by dephiros** [comment]
Hi @kevinbarabash 

Thank you for the quick response.

Just realized that I install `flow-to-ts` instead of installing `@khanacademy/flow-to-ts` 🤦🏼‍♂️

Have a great weekend,
An
